[package]
name = "emojify"
version = "0.1.3"
edition = "2024"
description = "emojify text to clipboard"
licence = "MIT"
authors = ["Attila Repka"]

[package.metadata.deb]
revision = ""


[dependencies]
arboard = "3.6.1"
clap = { version = "4.5.54", features = ["derive"] }
